FROM golang:1.26 AS builder

WORKDIR /app
ENV CGO_ENABLED=0 GOOS=linux GOTMPDIR=/go/tmp GOCACHE=/go/cache
RUN mkdir -p /go/tmp /go/cache
COPY . .

RUN go build -o worker ./cmd/worker

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/worker .

CMD ["./worker"]
