apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: mr-master:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
          env:
            - name: INPUT_PATH
              value: ""
            - name: WORKERS_COUNT
              value: "5"
            - name: MAPPERS_COUNT
              value: "5"
            - name: REDUCERS_COUNT
              value: "2"
            - name: GOMR_ROLLOUT_ID
              value: ""
